### ISSUE TITLE
Is there an alternative ppx for ppxlib?

### ISSUE THREAD

**Issue by Lupus** [janestreet/ppx_traverse#2]
I'm working on some AST definitions (not for OCaml) and looks like ppx_traverse is a great way to define mappers for AST structure. Is there generic deriver with same functionality available for ppxlib?

**Comment by ghost** [comment]
Yes, `ppxlib.traverse` :)

**Comment by Lupus** [comment]
Wow, cool! I should've searched harder. Thanks!
